# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaySlipInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadedDate', models.DateField(verbose_name=b'02-04-2017')),
                ('employeeName', models.CharField(max_length=256)),
                ('emailId', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=256)),
                ('designation', models.CharField(max_length=256)),
                ('month', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=20)),
                ('basic', models.FloatField()),
                ('hra', models.FloatField()),
                ('conveyance', models.FloatField()),
                ('specialAllowance', models.FloatField()),
                ('ot', models.FloatField()),
                ('lta', models.FloatField()),
                ('odr', models.FloatField()),
                ('arrears', models.FloatField()),
                ('educationAllowance', models.FloatField()),
                ('medicalAllowance', models.FloatField()),
                ('grossEarnings', models.FloatField()),
                ('providentFund', models.FloatField()),
                ('esi', models.FloatField()),
                ('professionalTax', models.FloatField()),
                ('incomeTax', models.FloatField()),
                ('salaryAdvance', models.FloatField()),
                ('cug', models.FloatField()),
                ('lwf', models.FloatField()),
                ('otherDeductions', models.FloatField()),
                ('arrearsPFDeduction', models.FloatField()),
                ('arrearsESIDeduction', models.FloatField()),
                ('totalDeduction', models.FloatField()),
                ('netPay', models.FloatField()),
                ('emailStatus', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PaySlipUploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbVersion', models.CharField(default=b'1.0', max_length=20)),
                ('uploadedAt', models.DateTimeField()),
                ('uploadedUser', models.CharField(max_length=256)),
                ('noOfRecords', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='smtpStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name=b'02-04-2017')),
                ('noOfMails', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='payslipinfo',
            name='uploadId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrOperations.PaySlipUploads'),
        ),
    ]
