# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrOperations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smtpstatus',
            name='date',
            field=models.DateField(default=b'02-04-2017'),
        ),
    ]
