# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-10 09:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrOperations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslipinfo',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 10, 9, 47, 49, 764473)),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='modifiedAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 10, 9, 47, 49, 764521)),
        ),
        migrations.AlterField(
            model_name='payslipuploads',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 10, 9, 47, 49, 764473)),
        ),
        migrations.AlterField(
            model_name='payslipuploads',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payslipuploads',
            name='modifiedAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 10, 9, 47, 49, 764521)),
        ),
        migrations.AlterField(
            model_name='smtpstatus',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 10, 9, 47, 49, 764473)),
        ),
        migrations.AlterField(
            model_name='smtpstatus',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='smtpstatus',
            name='modifiedAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 10, 9, 47, 49, 764521)),
        ),
    ]
