# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-04 10:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrOperations', '0010_auto_20170623_0851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payslipinfo',
            old_name='arrears',
            new_name='carMaintenance',
        ),
        migrations.AddField(
            model_name='payslipinfo',
            name='driverSalary',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslipinfo',
            name='earnedBasicAndDa',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslipinfo',
            name='earnedCarMaintenance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslipinfo',
            name='earnedConveyance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslipinfo',
            name='earnedDriverSalary',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslipinfo',
            name='earnedEduAllow',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslipinfo',
            name='earnedFuelReimbursement',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslipinfo',
            name='earnedHouseMaintenance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslipinfo',
            name='earnedHouseRentAllowance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslipinfo',
            name='earnedIncrement',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslipinfo',
            name='earnedLeaveTravelAllowance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslipinfo',
            name='earnedMedAllowance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslipinfo',
            name='earnedOt',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslipinfo',
            name='earnedOtherDeductionReimbt',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslipinfo',
            name='earnedSpecialAllowance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslipinfo',
            name='fuelReimbursement',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslipinfo',
            name='houseMaintenance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslipinfo',
            name='incentives',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslipinfo',
            name='increment',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 4, 10, 31, 4, 241037)),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='modifiedAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 4, 10, 31, 4, 241087)),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='uploadedDate',
            field=models.DateField(verbose_name=datetime.date(2017, 7, 4)),
        ),
        migrations.AlterField(
            model_name='payslipuploads',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 4, 10, 31, 4, 241037)),
        ),
        migrations.AlterField(
            model_name='payslipuploads',
            name='modifiedAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 4, 10, 31, 4, 241087)),
        ),
        migrations.AlterField(
            model_name='smtpstatus',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 4, 10, 31, 4, 241037)),
        ),
        migrations.AlterField(
            model_name='smtpstatus',
            name='date',
            field=models.DateField(default=datetime.date(2017, 7, 4)),
        ),
        migrations.AlterField(
            model_name='smtpstatus',
            name='modifiedAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 4, 10, 31, 4, 241087)),
        ),
    ]
