# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-04 10:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrOperations', '0011_auto_20170704_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslipinfo',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 4, 10, 40, 53, 276649)),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='modifiedAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 4, 10, 40, 53, 276700)),
        ),
        migrations.AlterField(
            model_name='payslipuploads',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 4, 10, 40, 53, 276649)),
        ),
        migrations.AlterField(
            model_name='payslipuploads',
            name='modifiedAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 4, 10, 40, 53, 276700)),
        ),
        migrations.AlterField(
            model_name='smtpstatus',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 4, 10, 40, 53, 276649)),
        ),
        migrations.AlterField(
            model_name='smtpstatus',
            name='modifiedAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 4, 10, 40, 53, 276700)),
        ),
    ]
