# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-04 17:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrOperations', '0014_auto_20170704_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslipinfo',
            name='earnedIncentives',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='arrearsESIDeduction',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='arrearsPFDeduction',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='basic',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='carMaintenance',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='conveyance',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 4, 17, 32, 28, 718267)),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='cug',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='driverSalary',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='earnedBasicAndDa',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='earnedCarMaintenance',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='earnedConveyance',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='earnedDriverSalary',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='earnedEduAllow',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='earnedFuelReimbursement',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='earnedHouseMaintenance',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='earnedHouseRentAllowance',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='earnedIncrement',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='earnedLeaveTravelAllowance',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='earnedMedAllowance',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='earnedOt',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='earnedOtherDeductionReimbt',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='earnedSpecialAllowance',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='educationAllowance',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='effectiveWorkDays',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='esi',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='fuelReimbursement',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='grossEarnings',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='houseMaintenance',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='hra',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='incentives',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='incomeTax',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='increment',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='lta',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='lwf',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='medicalAllowance',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='modifiedAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 4, 17, 32, 28, 718329)),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='odr',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='ot',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='otherDeductions',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='professionalTax',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='providentFund',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='salaryAdvance',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='specialAllowance',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='totalDeduction',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslipuploads',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 4, 17, 32, 28, 718267)),
        ),
        migrations.AlterField(
            model_name='payslipuploads',
            name='modifiedAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 4, 17, 32, 28, 718329)),
        ),
        migrations.AlterField(
            model_name='smtpstatus',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 4, 17, 32, 28, 718267)),
        ),
        migrations.AlterField(
            model_name='smtpstatus',
            name='modifiedAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 4, 17, 32, 28, 718329)),
        ),
    ]
