# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-05 16:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrOperations', '0016_auto_20170704_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslipinfo',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 5, 16, 42, 33, 651990)),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='earnedIncentives',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='modifiedAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 5, 16, 42, 33, 652053)),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='uploadedDate',
            field=models.DateField(verbose_name=datetime.date(2017, 7, 5)),
        ),
        migrations.AlterField(
            model_name='payslipuploads',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 5, 16, 42, 33, 651990)),
        ),
        migrations.AlterField(
            model_name='payslipuploads',
            name='modifiedAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 5, 16, 42, 33, 652053)),
        ),
        migrations.AlterField(
            model_name='smtpstatus',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 5, 16, 42, 33, 651990)),
        ),
        migrations.AlterField(
            model_name='smtpstatus',
            name='date',
            field=models.DateField(default=datetime.date(2017, 7, 5)),
        ),
        migrations.AlterField(
            model_name='smtpstatus',
            name='modifiedAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 5, 16, 42, 33, 652053)),
        ),
    ]
