# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-14 05:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrOperations', '0017_auto_20170705_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslipinfo',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 14, 5, 1, 14, 254731)),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='modifiedAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 14, 5, 1, 14, 254867)),
        ),
        migrations.AlterField(
            model_name='payslipinfo',
            name='uploadedDate',
            field=models.DateField(verbose_name=datetime.date(2017, 7, 14)),
        ),
        migrations.AlterField(
            model_name='payslipuploads',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 14, 5, 1, 14, 254731)),
        ),
        migrations.AlterField(
            model_name='payslipuploads',
            name='modifiedAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 14, 5, 1, 14, 254867)),
        ),
        migrations.AlterField(
            model_name='smtpstatus',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 14, 5, 1, 14, 254731)),
        ),
        migrations.AlterField(
            model_name='smtpstatus',
            name='date',
            field=models.DateField(default=datetime.date(2017, 7, 14)),
        ),
        migrations.AlterField(
            model_name='smtpstatus',
            name='modifiedAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 14, 5, 1, 14, 254867)),
        ),
    ]
