from datetime import datetime
from django.db import models
from payslipsproject.settings import DB_VERSION
from payslipsproject.models import CustomModel

__author__ = 'oliverqueen'


class PaySlipUploads(CustomModel):
    dbVersion = models.CharField(max_length=20, default=DB_VERSION[-1])
    uploadedAt = models.DateTimeField()
    uploadedUser = models.CharField(max_length=256)
    noOfRecords = models.CharField(max_length=256)

class PaySlipInfo(CustomModel):
    uploadId = models.ForeignKey(PaySlipUploads)
    uploadedDate = models.DateField(datetime.now().date())
    employeeName = models.CharField(max_length=256)
    emailId = models.EmailField()
    department = models.CharField(max_length=256)
    designation = models.CharField(max_length=256)
    month = models.CharField(max_length=20)
    year = models.CharField(max_length=20)
    basic = models.CharField(max_length=20, default="")
    hra = models.CharField(max_length=20, default="")
    conveyance = models.CharField(max_length=20, default="")
    specialAllowance = models.CharField(max_length=20, default="")
    ot = models.CharField(max_length=20, default="")
    lta = models.CharField(max_length=20, default="")
    odr = models.CharField(max_length=20, default="")
    increment = models.CharField(max_length=20, default="")
    educationAllowance = models.CharField(max_length=20, default="")
    medicalAllowance = models.CharField(max_length=20, default="")
    grossEarnings = models.CharField(max_length=20, default="")
    providentFund = models.CharField(max_length=20, default="")
    esi = models.CharField(max_length=20, default="")
    professionalTax = models.CharField(max_length=20, default="")
    incomeTax = models.CharField(max_length=20, default="")
    salaryAdvance = models.CharField(max_length=20, default="")
    cug = models.CharField(max_length=20, default="")
    lwf = models.CharField(max_length=20, default="")
    otherDeductions = models.CharField(max_length=20, default="")
    arrearsPFDeduction = models.CharField(max_length=20, default="")
    arrearsESIDeduction = models.CharField(max_length=20, default="")
    totalDeduction = models.CharField(max_length=20, default="")
    emailStatus = models.BooleanField(default=False)
    employeeNumber = models.CharField(max_length=20, default="Not Provided")
    bankName = models.CharField(max_length=256,default="IDBI")
    bankAccountNumber = models.CharField(max_length=256,default="Not Provided")
    panNumber = models.CharField(max_length=30, default="Not Provided")
    ppfNumber = models.CharField(max_length=30, default="Not Provided")
    location = models.CharField(max_length=30, default="KUKATPALLY")
    effectiveWorkDays = models.CharField(max_length=20, default="")
    earnedBasicAndDa = models.CharField(max_length=20, default="")
    earnedHouseRentAllowance = models.CharField(max_length=20, default="")
    earnedConveyance = models.CharField(max_length=20, default="")
    earnedSpecialAllowance = models.CharField(max_length=20, default="")
    earnedOt = models.CharField(max_length=20, default="")
    earnedLeaveTravelAllowance = models.CharField(max_length=20, default="")
    earnedOtherDeductionReimbt = models.CharField(max_length=20, default="")
    earnedIncrement = models.CharField(max_length=20, default="")
    earnedEduAllow = models.CharField(max_length=20, default="")
    earnedMedAllowance = models.CharField(max_length=20, default="")
    houseMaintenance = models.CharField(max_length=20, default="")
    earnedHouseMaintenance = models.CharField(max_length=20, default="")
    driverSalary = models.CharField(max_length=20, default="")
    earnedDriverSalary = models.CharField(max_length=20, default="")
    carMaintenance = models.CharField(max_length=20, default="")
    earnedCarMaintenance = models.CharField(max_length=20, default="")
    fuelReimbursement = models.CharField(max_length=20, default="")
    earnedFuelReimbursement = models.CharField(max_length=20, default="")
    incentives = models.CharField(max_length=20, default="")
    earnedIncentives = models.CharField(max_length=20, default="")
    actualGrossEarnings = models.FloatField()
    totalNetPay = models.FloatField()

class smtpStatus(CustomModel):
    date = models.DateField(default=datetime.now().date())
    noOfMails = models.IntegerField(default=0)